version: "3"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    env_file:
      - config.env
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8000:8000"
    env_file:
      - config.env
    volumes:
      - ./:/application
volumes:
  db_data:
    driver: local
  cache:
    driver: local