version: "3"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    env_file:
      - config.env
    ports:
      - "5432:5432"
  fake-s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ../:/fake-s3
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: poetry run uvicorn src.api:app --host 0.0.0.0 --port 8000
    env_file:
      - config.env
    volumes:
      - ./:/application
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db_data:
    external: true
    driver: local
  cache:
    driver: local