version: "3"
services:
  db-test:
    image: postgres
    env_file:
      - config.test.env
    ports:
      - "5433:5433"
    command: -p 5433
  tests:
    depends_on:
      - db-test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config.test.env
    volumes:
      - ./:/application