version: "3"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - config.env
    ports:
      - "5432:5432"
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=0
      - PERSISTENCE=1
      - SERVICES=s3
    volumes:
      - localstack:/var/lib/localstack
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: poetry run uvicorn src.api:app --host 0.0.0.0 --port 8000
    env_file:
      - config.env
    volumes:
      - ./:/application
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db_data:
    driver: local
